
  CREATE TABLE "A22164003"."STORES" 
   (	"STOREID" NUMBER(*,0), 
	"STORENAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ST" PRIMARY KEY ("STOREID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("STORENAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE TABLE "A22164003"."SUPPLIERS" 
   (	"SUPPLIERID" NUMBER(*,0), 
	"SUPPLIERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"SUPPLIEREMAIL" VARCHAR2(30 BYTE), 
	"SUPPLIERPHONE" VARCHAR2(20 BYTE), 
	"SUPPLIERTYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SUPPLIERBRAND" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SUPPLIERACCOUNT" NUMBER(8,4) NOT NULL ENABLE, 
	 CONSTRAINT "PK_SU" PRIMARY KEY ("SUPPLIERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("SUPPLIEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("SUPPLIERPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE TABLE "A22164003"."CUSTOMERS" 
   (	"CUSTOMERID" NUMBER(*,0), 
	"CUSTOMERNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CUSTOMEREMAIL" VARCHAR2(30 BYTE), 
	"CUSTOMERPHONE" VARCHAR2(20 BYTE), 
	"CUSTOMERTYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CUSTOMERACCOUNT" NUMBER(8,4) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CU" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("CUSTOMEREMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("CUSTOMERPHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
   CREATE TABLE "A22164003"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(10 BYTE), 
	"USERPASSWORD" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FULLNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"LOGIN" NUMBER(1,0) DEFAULT 1, 
	 CONSTRAINT "PK_U" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CHECK (login in (1,0)) ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;


  CREATE TABLE "A22164003"."DEPARTMENTS" 
   (	"DEPARTMENTID" NUMBER(*,0), 
	"DEPARTMENTNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PK_D" PRIMARY KEY ("DEPARTMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

   CREATE TABLE "A22164003"."UNITS" 
   (	"UNITID" NUMBER(*,0), 
	"UNITCODE" VARCHAR2(10 BYTE), 
	"UNITDESC" VARCHAR2(300 BYTE), 
	 CONSTRAINT "PK_UN" PRIMARY KEY ("UNITID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 UNIQUE ("UNITCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

  CREATE TABLE "A22164003"."ITEMS" 
   (	"ITEMID" NUMBER(*,0), 
	"ITEMNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"ITEMNUMBER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"STOREID" NUMBER(*,0), 
	"UNITID" NUMBER(*,0), 
	"UNITPRICE" NUMBER, 
	 CONSTRAINT "PK_IT" PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "F_K_I_S" FOREIGN KEY ("STOREID")
	  REFERENCES "A22164003"."STORES" ("STOREID") ENABLE, 
	 CONSTRAINT "F_K_I_U" FOREIGN KEY ("UNITID")
	  REFERENCES "A22164003"."UNITS" ("UNITID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE TABLE "A22164003"."RECEIVING" 
   (	"RECEIVEID" NUMBER(*,0), 
	"SUPPLIERID" NUMBER(*,0) NOT NULL ENABLE, 
	"RECEIVENUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"RECEIVEDATE" DATE, 
	"STOREID" NUMBER(*,0), 
	"DEPARTMENTID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"TOTALPRICE" NUMBER(8,4) NOT NULL ENABLE, 
	 CONSTRAINT "PK_R" PRIMARY KEY ("RECEIVEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_R_S" FOREIGN KEY ("STOREID")
	  REFERENCES "A22164003"."STORES" ("STOREID") ENABLE, 
	 CONSTRAINT "FK_R_D" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "A22164003"."DEPARTMENTS" ("DEPARTMENTID") ENABLE, 
	 CONSTRAINT "FK_R_SU" FOREIGN KEY ("SUPPLIERID")
	  REFERENCES "A22164003"."SUPPLIERS" ("SUPPLIERID") ENABLE, 
	 CONSTRAINT "FK_R_U" FOREIGN KEY ("USERID")
	  REFERENCES "A22164003"."USERS" ("USERID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE TABLE "A22164003"."RECEIVINGITMES" 
   (	"RECEIVETTEMID" NUMBER(*,0), 
	"RECEIVEID" NUMBER(*,0) NOT NULL ENABLE, 
	"ITEMID" NUMBER(*,0) NOT NULL ENABLE, 
	"RECEIVESERIAL" NUMBER(*,0) NOT NULL ENABLE, 
	"UNITPRICE" NUMBER(5,4) NOT NULL ENABLE, 
	"RECEIVEQUANTITY" NUMBER(*,0), 
	 CONSTRAINT "PK_RE" PRIMARY KEY ("RECEIVETTEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_R_RE" FOREIGN KEY ("RECEIVEID")
	  REFERENCES "A22164003"."RECEIVING" ("RECEIVEID") ENABLE, 
	 CONSTRAINT "FK_R_IT" FOREIGN KEY ("ITEMID")
	  REFERENCES "A22164003"."ITEMS" ("ITEMID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE TABLE "A22164003"."SALES" 
   (	"SALEID" NUMBER(*,0), 
	"CUSTOMERID" NUMBER(*,0) NOT NULL ENABLE, 
	"SALENUMBER" NUMBER(*,0) NOT NULL ENABLE, 
	"SALEDATE" DATE, 
	"STOREID" NUMBER(*,0), 
	"DEPARTMENTID" NUMBER(*,0), 
	"USERID" NUMBER(*,0), 
	"TOTALPRICE" NUMBER(8,4) NOT NULL ENABLE, 
	 CONSTRAINT "PK_I" PRIMARY KEY ("SALEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_I_S" FOREIGN KEY ("STOREID")
	  REFERENCES "A22164003"."STORES" ("STOREID") ENABLE, 
	 CONSTRAINT "FK_I_D" FOREIGN KEY ("DEPARTMENTID")
	  REFERENCES "A22164003"."DEPARTMENTS" ("DEPARTMENTID") ENABLE, 
	 CONSTRAINT "FK_I_U" FOREIGN KEY ("USERID")
	  REFERENCES "A22164003"."USERS" ("USERID") ENABLE, 
	 CONSTRAINT "FK_C_I" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "A22164003"."CUSTOMERS" ("CUSTOMERID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE TABLE "A22164003"."SALESITEMS" 
   (	"SALESITEMID" NUMBER(*,0), 
	"SALEID" NUMBER(*,0) NOT NULL ENABLE, 
	"SALESERIAL" NUMBER(*,0) NOT NULL ENABLE, 
	"UNITPRICE" NUMBER(5,4) NOT NULL ENABLE, 
	"SALEQUANTITY" NUMBER(*,0), 
	"ITEMID" NUMBER(*,0) NOT NULL ENABLE, 
	"AVAILABLEQUANTITY" NUMBER(*,0), 
	 CONSTRAINT "PK_IS" PRIMARY KEY ("SALESITEMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_I_IT" FOREIGN KEY ("ITEMID")
	  REFERENCES "A22164003"."ITEMS" ("ITEMID") ENABLE, 
	 CONSTRAINT "FK_I_IS" FOREIGN KEY ("SALEID")
	  REFERENCES "A22164003"."SALES" ("SALEID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
   CREATE TABLE "A22164003"."TRANSACTIONS" 
   (	"TRANSACTIONID" NUMBER(*,0), 
	"TRANSACTIONTYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"TRANSACTIONDATE" DATE, 
	"ITEMID" NUMBER(*,0), 
	"UNITPRICE" NUMBER(5,4) NOT NULL ENABLE, 
	"GTYPLUS" NUMBER(*,0), 
	"GTYMINUS" NUMBER(*,0), 
	"TRANSACTIONNUMBER" NUMBER, 
	 CONSTRAINT "PK_T" PRIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_T_I" FOREIGN KEY ("ITEMID")
	  REFERENCES "A22164003"."ITEMS" ("ITEMID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

 

 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_CUSTOMERS" ("CUSTOMERID", "CUSTOMERNAME", "CUSTOMEREMAIL", "CUSTOMERPHONE", "CUSTOMERTYPE", "CUSTOMERACCOUNT") AS 
  select "CUSTOMERID","CUSTOMERNAME","CUSTOMEREMAIL","CUSTOMERPHONE","CUSTOMERTYPE","CUSTOMERACCOUNT" from CUSTOMERS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_RECEIVINGITMES" ("RECEIVETTEMID", "RECEIVEID", "ITEMID", "RECEIVESERIAL", "UNITPRICE", "RECEIVEQUANTITY") AS 
  select "RECEIVETTEMID","RECEIVEID","ITEMID","RECEIVESERIAL","UNITPRICE","RECEIVEQUANTITY" from RECEIVINGITMES;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_RECEIVING" ("RECEIVEID", "SUPPLIERID", "RECEIVENUMBER", "RECEIVEDATE", "STOREID", "DEPARTMENTID", "USERID", "TOTALPRICE") AS 
  select "RECEIVEID","SUPPLIERID","RECEIVENUMBER","RECEIVEDATE","STOREID","DEPARTMENTID","USERID","TOTALPRICE" from RECEIVING;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_DEPARTMENTS" ("DEPARTMENTID", "DEPARTMENTNAME") AS 
  select "DEPARTMENTID","DEPARTMENTNAME" from DEPARTMENTS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_SALES" ("SALEID", "CUSTOMERID", "SALENUMBER", "SALEDATE", "STOREID", "DEPARTMENTID", "USERID", "TOTALPRICE") AS 
  select "SALEID","CUSTOMERID","SALENUMBER","SALEDATE","STOREID","DEPARTMENTID","USERID","TOTALPRICE" from SALES;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_ITEMS" ("ITEMID", "ITEMNAME", "ITEMNUMBER", "STOREID", "UNITID", "UNITPRICE") AS 
  select "ITEMID","ITEMNAME","ITEMNUMBER","STOREID","UNITID","UNITPRICE" from ITEMS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_SALESITEMS" ("SALESITEMID", "SALEID", "SALESERIAL", "UNITPRICE", "SALEQUANTITY", "ITEMID", "AVAILABLEQUANTITY") AS 
  select "SALESITEMID","SALEID","SALESERIAL","UNITPRICE","SALEQUANTITY","ITEMID","AVAILABLEQUANTITY" from SALESITEMS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_STORES" ("STOREID", "STORENAME") AS 
  select "STOREID","STORENAME" from STORES;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_SUPPLIERS" ("SUPPLIERID", "SUPPLIERNAME", "SUPPLIEREMAIL", "SUPPLIERPHONE", "SUPPLIERTYPE", "SUPPLIERBRAND", "SUPPLIERACCOUNT") AS 
  select "SUPPLIERID","SUPPLIERNAME","SUPPLIEREMAIL","SUPPLIERPHONE","SUPPLIERTYPE","SUPPLIERBRAND","SUPPLIERACCOUNT" from SUPPLIERS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_TRANSACTIONS" ("TRANSACTIONID", "TRANSACTIONTYPE", "TRANSACTIONNUMBER", "TRANSACTIONDATE", "ITEMID", "UNITPRICE", "GTYPLUS", "GTYMINUS") AS 
  select "TRANSACTIONID","TRANSACTIONTYPE","TRANSACTIONNUMBER","TRANSACTIONDATE","ITEMID","UNITPRICE","GTYPLUS","GTYMINUS" from TRANSACTIONS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_UNITS" ("UNITID", "UNITCODE", "UNITDESC") AS 
  select "UNITID","UNITCODE","UNITDESC" from UNITS;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."V_USERS" ("USERID", "USERNAME", "USERPASSWORD", "FULLNAME", "LOGIN") AS 
  select "USERID","USERNAME","USERPASSWORD","FULLNAME","LOGIN" from users;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."VRECEIVING" ("SUPPLIERID", "DECE", "RECEIVEID", "RECEIVEDATE", "QUANTITY", "TOTALPRICE") AS 
  select 
S.SUPPLIERID ,
case grouping_id(R.RECEIVEID ,RECEIVEDATE)
  when 0 then '??????? ???? ??????? ???? ????????'
  when 1 then '??????? ???? ???????? '
  when 2 then '??????? ???? ???????'
  when 3 then '  ?????? ?????????'end dece,
R.RECEIVEID ,RECEIVEDATE  , sum(RECEIVEQUANTITY) QUANTITY ,sum(UNITPRICE) TOTALPRICE
from RECEIVING R ,RECEIVINGITMES I , SUPPLIERS S
where R.RECEIVEID = I.RECEIVEID 
group by S.SUPPLIERID ,cube(R.RECEIVEID ,RECEIVEDATE) 
order by 3;
 
  CREATE OR REPLACE FORCE VIEW "A22164003"."VSALES" ("CUSTOMERID", "DECE", "SALEID", "SALEDATE", "TOTALPRICE", "QUANTITY") AS 
  select  CU.CUSTOMERID, 
case grouping_id(s.SALEID ,SALEDATE)
  when 0 then '??????? ???? ??????? ???? ????????'
  when 1 then '??????? ???? ???????? '
  when 2 then '??????? ???? ???????'
  when 3 then '  ?????? ???????? 'end dece,
  s.SALEID ,SALEDATE ,sum(UNITPRICE) TOTALPRICE,sum(SALEQUANTITY) QUANTITY
from SALES s, SALESITEMS i ,CUSTOMERS CU
where s.SALEID = i.SALEID 
and CU.CUSTOMERID = s.CUSTOMERID
group by CU.CUSTOMERID,cube(s.SALEID ,SALEDATE ) 
order by 3;

 insert into USERS (1,'4003','4003','Abdullah Abdulkhaleq',0);
 insert into USERS (2,'1','1','mohammed Abdulkhaleq',0);